### ISSUE TITLE
elec pol4 instuctions problem

### ISSUE THREAD

**Issue by Ceasea** [aoterodelaroza/gibbs2#1]
Hi @aoterodelaroza,

In page 27, it is hard for me to understand the sentences. I would like to get some help here.
>Usually, one fits the total free energy with respect to volue to find the first four and the smearing -T*S contribution to find the last four.
>
Fistly, the word "volue" should be "volume", right?
If so, I saw there are 8 coeffeicents for each volume in the ./dat/al_lda/al.res you provide.
That means I should fit the total energy to the "volume" at a certain "volume". That really confused me. 

Or, the "volue" means the smearing-width. I should fit total energy to the smearing-width at a certain volume.

Additionally, I was wondering if this fitting process could be integrated into Gibbs2 and the uses are asked to provide corresponding data if elec is used.

thanks a lot.
Ceasea.

**Comment by aoterodelaroza** [comment]
Hi @ceasea. I can't find the "volue" typo in the current manual,
sorry. If you have not done so, I suggest git pulling to the latest
version. But yes, it was probably volume.

> If so, I saw there are 8 coeffeicents for each volume in the
> ./dat/al_lda/al.res you provide.  That means I should fit the total
> energy to the "volume" at a certain "volume". That really confused
> me.  Or, the "volue" means the smearing-width. I should fit total
> energy to the smearing-width at a certain volume.

I don't think it is either of those things. At each volume, the first
four columns give the temperature dependence of Fel as a function of
temperature using a fourth-degree polynomial. From the manual:

Fel = i4 * T^4 + i3 * T^3 + i2 * T^2 + i1 * T

where i1 is the icol.i integer in the pol4 keyword, i2 is icol.i+1,
etc. The next four columns are the fourth degree polynomial -T*Sel at
the corresponding volume:

-T*S_el = i5 * T^4 + i6 * T^3 + i7 * T^2 + i8 * T

where i5=icol.i+4, etc. To find these coefficients, run the same
calculation at the same geometry for different temperatures
(i.e. smearing widths) and then fit your results. This needs to be
repeated at every volume in the grid and then fitted using some other
program (e.g. octave).

I have made some tweaks to the manual to clarify this section, which
was not well written.

> Additionally, I was wondering if this fitting process could be
> integrated into Gibbs2 and the uses are asked to provide
> corresponding data if elec is used. 

It could, but as you can see from above it is a lot of data and I
would not like to have to read the energies straight from the output
of the electronic structure program (because there are many of
those). Also, the Fel contribution is usually so small compared to the
Fvib that I normally go for Sommerfeld, if at all. However, if you
want to modify gibbs2 to do this, I would be glad to see it.

**Comment by aoterodelaroza** [comment]
Also, if you use or touch that code, note that I have not personally
used that part of gibbs2 for a number of years, so I suggest keeping
an eye out for bugs and strange things.

**Comment by Ceasea** [comment]
okay,i see. thank you for the detail.
