### ISSUE TITLE
phDOS renormalization

### ISSUE THREAD

**Issue by martok** [aoterodelaroza/gibbs2#2]
Hello,

while looking for something else, I noticed a possible issue in phDOS renormalization:
https://github.com/aoterodelaroza/gibbs2/blob/f126b0d13e89e3c7e025ed484edc2d27b6fc07d1/src/varbas.f90#L2181

Shouldn't that be `... / sumn * (3d0 * vfree *  p%z)`, as in the conditional five lines before?

Best,
Sebastian

**Comment by aoterodelaroza** [comment]
Hi @martok, I think I did change this bit of code recently because of the warning message. But my impression is that it is correct, though. Internally, gibbs2 uses for all extensive properties an amount of matter equal to vfree atoms. When a new phase is passed to the program with Z /= 1, then the volume and the energy are divided by Z in order for them to correspond to vfree atoms and to have those extensive properties be comparable to the other phases. With this choice, the phdos should be renormalized to 3*vfree, effectively dividing the phdos in input and the subsequent extensive properties calculated from it (Fvib, etc.) by the Z of the phase. Note, however, that in the warning message above I keep the Z in order to make it more understandable to the user, since they will be expecting the phdos should integrate to 3 times the number of atoms in their cell. Does this make sense?

**Comment by martok** [comment]
Hm, that sounds reasonable. I must admit, I don't use Z!=1 because it confuses me more than anything, but it looked a bit odd in the code.
But I you're right, it should be the number of atoms in the reference cell, and that is already scaled.

Thank you for clearing that up, and sorry for the noise!

**Comment by aoterodelaroza** [comment]
Not at all! It's good to know that potential bugs don't go unnoticed. :)
