### ISSUE TITLE
set nat.i and z.r in system with impurity

### ISSUE THREAD

**Issue by Ceasea** [aoterodelaroza/gibbs2#3]
Hi @aoterodelaroza 

I met a problem when calculating systems with impurity.
And I couldn't find a better answer in the manual.

For example,
when we calculate a fcc Al system, the input file should be,

>  mm 26.9815
nat 1
phase ...  tmodel debye_gruneisen ...

When we want to calculate the Al16H,
H atom breaks the symmetry of fcc-Al16, so there is no the same basic unit of repetion.
The input file i guess may be 
>  mm 26.9815*16+ 1
nat 17
phase ... tmodel debye_gruneisen ..

The two inputs lead to uncompatible result for Cp, Cv properties.
Indrectly, we need to divided Cp or Cp by the (26.9815*16+1)/26.9815 (or 17/1, I guess) to make the Cp or Cv of Al16H compatible with that of pure fcc-Al.

Is there a better(right) way to make the results compatible?
Thanks.

**Comment by aoterodelaroza** [comment]
Hi @Ceasea, 

Yes, this is a common theme that I think needs to be clarified in the
manual and using an example. In gibbs2, all the extensive properties
(Cp and Cv but also energies, volumes, etc.) are given referred to an
amount of matter that has `nat` atoms and `mm` mass. For instance, as
you say, fcc Al should have `nat = 1` and `mm = 26.9815`. 

In the case when you have several phases of the same compound, you
need to use the Z keyword for PHASE. Imagine phase A has a primitive
unit cell with 4 atoms and phase B has primitive cell with 8
atoms. Your input should have `nat = 4` and the `mm` corresponding to
the molar mass of those 4 atoms, and then `Z = 1` for A and `Z = 2`
for B, since the latter's primitive cell has 8 atoms instead of
4. Internally, gibbs2 divides all extensive properties on input, like
the energy or the volume, by the Z provided by the user. On output,
all extensive properties correspond to `nat` atoms and `mm` mass. If,
for instance, you have an addition phase C with 16 atoms, then the Z
for that phase is Z = 16/4 = 4. And so on.

In your case, I do not think pure Al and impure Al are directly
comparable, since they have different stoichiometries (you would need
to add to the pure Al some other phase representing pure H). That
said, if you are just looking at Cp and Cv, then what you can do is
define impure Al as `nat = 17` and `mm = 26.9815*16+1`, just as you
are doing, and pure Al as `nat = 16`, `mm = 26.9815*16` with 
a Z = 1/16 for the fcc Al phase. It is a bit of a dirty hack, but it
should work. In any case, I strongly recommend comparing intensive
properties between both phases.

**Comment by Ceasea** [comment]
Ok, I understand.
Thanks for the answer in detail.
